name: GitHub Pages

on: [ workflow_dispatch ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4

      - name: Get artifacts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          gh release download test

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
